// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoItikx_hO73ukwXY6Z-n-M_jysedeHuE',
    appId: '1:65994541903:web:059f3b3c3f54e459d9533a',
    messagingSenderId: '65994541903',
    projectId: 'project-6d3ff',
    authDomain: 'project-6d3ff.firebaseapp.com',
    databaseURL: 'https://project-6d3ff-default-rtdb.firebaseio.com',
    storageBucket: 'project-6d3ff.firebasestorage.app',
    measurementId: 'G-ELPYVVYTFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB275vsSNZgGK8RpEfciPme2R7OoR32TU',
    appId: '1:65994541903:android:a621668782c7190ed9533a',
    messagingSenderId: '65994541903',
    projectId: 'project-6d3ff',
    databaseURL: 'https://project-6d3ff-default-rtdb.firebaseio.com',
    storageBucket: 'project-6d3ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKJeygHinVCaaaCoxKNoljbi9NiOlN1kQ',
    appId: '1:65994541903:ios:4f9c163f15d1f40ad9533a',
    messagingSenderId: '65994541903',
    projectId: 'project-6d3ff',
    databaseURL: 'https://project-6d3ff-default-rtdb.firebaseio.com',
    storageBucket: 'project-6d3ff.firebasestorage.app',
    iosBundleId: 'com.example.spacescout2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKJeygHinVCaaaCoxKNoljbi9NiOlN1kQ',
    appId: '1:65994541903:ios:4f9c163f15d1f40ad9533a',
    messagingSenderId: '65994541903',
    projectId: 'project-6d3ff',
    databaseURL: 'https://project-6d3ff-default-rtdb.firebaseio.com',
    storageBucket: 'project-6d3ff.firebasestorage.app',
    iosBundleId: 'com.example.spacescout2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoItikx_hO73ukwXY6Z-n-M_jysedeHuE',
    appId: '1:65994541903:web:1096bd9a28aeade4d9533a',
    messagingSenderId: '65994541903',
    projectId: 'project-6d3ff',
    authDomain: 'project-6d3ff.firebaseapp.com',
    databaseURL: 'https://project-6d3ff-default-rtdb.firebaseio.com',
    storageBucket: 'project-6d3ff.firebasestorage.app',
    measurementId: 'G-9RPS6HGK6R',
  );

}