class HouseData {
  static Map<String, List<Map<String, dynamic>>> getHouseData() {
    return {
      "Recently Watched": [
        {
          "id": 1,
          "title": "Modern Downtown Loft",
          "image": "assets/house 1.jpg",
          "location": "Downtown LA, CA",
          "bedrooms": 2,
          "bathrooms": 2,
          "area": "1,200 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 3200,
          "buyPrice": 650000,
          "description": "Sleek modern loft with floor-to-ceiling windows and city skyline views",
          "amenities": ["City Views", "Rooftop Access", "Gym", "Concierge"],
          "isAvailable": true,
        },
        {
          "id": 2,
          "title": "Lake Tahoe Retreat",
          "image": "assets/house2.jpg",
          "location": "Lake Tahoe, CA",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,400 sq ft",
          "propertyType": "Cabin",
          "category": "Residential",
          "rentPrice": 2800,
          "buyPrice": 520000,
          "description": "Rustic yet modern cabin with panoramic lake views and private dock access",
          "amenities": ["Lake Views", "Private Dock", "Hot Tub", "Fireplace"],
          "isAvailable": true,
        },
        {
          "id": 3,
          "title": "Malibu Beach Estate",
          "image": "assets/house3.jpg",
          "location": "Malibu, CA",
          "bedrooms": 5,
          "bathrooms": 4,
          "area": "3,200 sq ft",
          "propertyType": "Villa",
          "category": "Residential",
          "rentPrice": 12000,
          "buyPrice": 4200000,
          "description": "Luxury beachfront estate with infinity pool and direct beach access",
          "amenities": ["Private Beach", "Infinity Pool", "Wine Cellar", "Home Theater"],
          "isAvailable": true,
        },
        {
          "id": 4,
          "title": "Beverly Hills Penthouse",
          "image": "assets/house5.jpg",
          "location": "Beverly Hills, CA",
          "bedrooms": 4,
          "bathrooms": 3,
          "area": "2,800 sq ft",
          "propertyType": "Penthouse",
          "category": "Residential",
          "rentPrice": 8500,
          "buyPrice": 1800000,
          "description": "Exclusive penthouse with 360-degree city and mountain views",
          "amenities": ["Panoramic Views", "Private Elevator", "Terrace", "Valet Parking"],
          "isAvailable": true,
        },
      ],
      "Hot deal": [
        {
          "id": 5,
          "title": "Cozy Studio Apartment",
          "image": "assets/house5.jpg",
          "location": "Hollywood, CA",
          "bedrooms": 1,
          "bathrooms": 1,
          "area": "650 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 1800,
          "buyPrice": 320000,
          "description": "Modern studio in the heart of Hollywood with great amenities",
          "amenities": ["Pool", "Gym", "Parking", "Rooftop Deck"],
          "isAvailable": true,
        },
        {
          "id": 6,
          "title": "Charming Duplex",
          "image": "assets/house6.jpg",
          "location": "Pasadena, CA",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,100 sq ft",
          "propertyType": "Townhouse",
          "category": "Residential",
          "rentPrice": 2200,
          "buyPrice": 380000,
          "description": "Beautiful duplex with private entrance and small garden",
          "amenities": ["Private Garden", "Garage", "Hardwood Floors"],
          "isAvailable": true,
        },
        {
          "id": 7,
          "title": "Fixer-Upper House",
          "image": "assets/house7.jpg",
          "location": "Long Beach, CA",
          "bedrooms": 2,
          "bathrooms": 1,
          "area": "900 sq ft",
          "propertyType": "House",
          "category": "Residential",
          "rentPrice": 1500,
          "buyPrice": 250000,
          "description": "Great investment opportunity in up-and-coming neighborhood",
          "amenities": ["Large Yard", "Parking", "Near Beach"],
          "isAvailable": true,
        },
        {
          "id": 8,
          "title": "Student Housing Unit",
          "image": "assets/house6.jpg",
          "location": "Westwood, CA",
          "bedrooms": 2,
          "bathrooms": 2,
          "area": "800 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 1600,
          "buyPrice": 420000,
          "description": "Perfect for students near UCLA with all utilities included",
          "amenities": ["Utilities Included", "WiFi", "Study Room", "Laundry"],
          "isAvailable": true,
        },
      ],
      "Countryside": [
        {
          "id": 9,
          "title": "Napa Valley Farmhouse",
          "image": "assets/house7.jpg",
          "location": "Napa Valley, CA",
          "bedrooms": 4,
          "bathrooms": 3,
          "area": "2,200 sq ft",
          "propertyType": "Farmhouse",
          "category": "Residential",
          "rentPrice": 3200,
          "buyPrice": 580000,
          "description": "Historic farmhouse surrounded by organic vineyards with tasting room",
          "amenities": ["Vineyard Views", "Wine Cellar", "Organic Garden", "Barn"],
          "isAvailable": true,
        },
        {
          "id": 10,
          "title": "Rustic Ranch House",
          "image": "assets/house 1.jpg",
          "location": "Sonoma, CA",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,600 sq ft",
          "propertyType": "House",
          "category": "Residential",
          "rentPrice": 2400,
          "buyPrice": 420000,
          "description": "Authentic ranch house with horse stables and riding trails",
          "amenities": ["Horse Stables", "Riding Trails", "Fireplace", "Large Deck"],
          "isAvailable": true,
        },
        {
          "id": 11,
          "title": "Countryside Cottage",
          "image": "assets/house3.jpg",
          "location": "Temecula, CA",
          "bedrooms": 2,
          "bathrooms": 1,
          "area": "1,000 sq ft",
          "propertyType": "Cottage",
          "category": "Residential",
          "rentPrice": 1800,
          "buyPrice": 320000,
          "description": "Charming cottage with wrap-around porch and fruit orchard",
          "amenities": ["Fruit Orchard", "Wrap-around Porch", "Wood Stove", "Pond"],
          "isAvailable": true,
        },
        {
          "id": 12,
          "title": "Mountain View Ranch",
          "image": "assets/house2.jpg",
          "location": "Big Bear, CA",
          "bedrooms": 5,
          "bathrooms": 3,
          "area": "2,800 sq ft",
          "propertyType": "Ranch",
          "category": "Residential",
          "rentPrice": 4200,
          "buyPrice": 750000,
          "description": "Spacious ranch with panoramic mountain views and private lake access",
          "amenities": ["Mountain Views", "Private Lake", "Hiking Trails", "Workshop"],
          "isAvailable": true,
        },
      ],
      "Near beach": [
        {
          "id": 13,
          "title": "Santa Monica Beach Condo",
          "image": "assets/house 1.jpg",
          "location": "Santa Monica, CA",
          "bedrooms": 2,
          "bathrooms": 2,
          "area": "1,200 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 4200,
          "buyPrice": 850000,
          "description": "Stunning ocean-view condo with private balcony and beach access",
          "amenities": ["Ocean View", "Private Balcony", "Beach Access", "Pool"],
          "isAvailable": true,
        },
        {
          "id": 14,
          "title": "Venice Beach Bungalow",
          "image": "assets/house2.jpg",
          "location": "Venice, CA",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,400 sq ft",
          "propertyType": "House",
          "category": "Residential",
          "rentPrice": 3800,
          "buyPrice": 720000,
          "description": "Charming bungalow walking distance to Venice Beach and canals",
          "amenities": ["Beach Access", "Rooftop Deck", "Garden", "Parking"],
          "isAvailable": true,
        },
        {
          "id": 15,
          "title": "Redondo Beach Townhouse",
          "image": "assets/house3.jpg",
          "location": "Redondo Beach, CA",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,300 sq ft",
          "propertyType": "Townhouse",
          "category": "Residential",
          "rentPrice": 3200,
          "buyPrice": 680000,
          "description": "Modern townhouse with marina views and private garage",
          "amenities": ["Marina Views", "Private Garage", "Patio", "Near Pier"],
          "isAvailable": true,
        },
        {
          "id": 16,
          "title": "Manhattan Beach Studio",
          "image": "assets/house5.jpg",
          "location": "Manhattan Beach, CA",
          "bedrooms": 1,
          "bathrooms": 1,
          "area": "700 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 2800,
          "buyPrice": 580000,
          "description": "Cozy studio with ocean breeze and walking distance to beach",
          "amenities": ["Ocean Breeze", "Beach Access", "Fitness Center", "Laundry"],
          "isAvailable": true,
        },
      ],
      "Iconic cities": [
        {
          "id": 17,
          "title": "SF Financial District Loft",
          "image": "assets/house5.jpg",
          "location": "San Francisco, CA",
          "bedrooms": 2,
          "bathrooms": 2,
          "area": "1,100 sq ft",
          "propertyType": "Penthouse",
          "category": "Residential",
          "rentPrice": 5200,
          "buyPrice": 1200000,
          "description": "Luxury loft with panoramic bay and city views in the heart of SF",
          "amenities": ["Bay Views", "High Ceilings", "Modern Kitchen", "Concierge"],
          "isAvailable": true,
        },
        {
          "id": 18,
          "title": "NYC Style Apartment",
          "image": "assets/house6.jpg",
          "location": "Downtown LA, CA",
          "bedrooms": 1,
          "bathrooms": 1,
          "area": "800 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 3800,
          "buyPrice": 750000,
          "description": "Industrial-style apartment with exposed brick and city skyline views",
          "amenities": ["City Views", "Exposed Brick", "Hardwood Floors", "Rooftop"],
          "isAvailable": true,
        },
        {
          "id": 19,
          "title": "Chicago-Style Condo",
          "image": "assets/house7.jpg",
          "location": "Chicago, IL",
          "bedrooms": 2,
          "bathrooms": 2,
          "area": "1,000 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 2800,
          "buyPrice": 450000,
          "description": "Modern condo in the Loop with lake and city views",
          "amenities": ["Lake Views", "City Views", "Gym", "Doorman"],
          "isAvailable": true,
        },
        {
          "id": 20,
          "title": "Miami Art Deco Studio",
          "image": "assets/house6.jpg",
          "location": "Miami Beach, FL",
          "bedrooms": 1,
          "bathrooms": 1,
          "area": "600 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 2200,
          "buyPrice": 380000,
          "description": "Historic Art Deco building with ocean views and vintage charm",
          "amenities": ["Ocean Views", "Art Deco Style", "Pool", "Beach Access"],
          "isAvailable": true,
        },
      ],
      "Amazing views": [
        {
          "id": 21,
          "title": "Mountain Peak Cabin",
          "image": "assets/house7.jpg",
          "location": "Big Bear, CA",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,800 sq ft",
          "propertyType": "Cabin",
          "category": "Residential",
          "rentPrice": 3500,
          "buyPrice": 520000,
          "description": "Spectacular mountain cabin with 360-degree views and private hiking trails",
          "amenities": ["360° Views", "Private Trails", "Hot Tub", "Fireplace"],
          "isAvailable": true,
        },
        {
          "id": 22,
          "title": "Cliffside Ocean Villa",
          "image": "assets/house 1.jpg",
          "location": "Monterey, CA",
          "bedrooms": 4,
          "bathrooms": 3,
          "area": "2,400 sq ft",
          "propertyType": "Villa",
          "category": "Residential",
          "rentPrice": 6800,
          "buyPrice": 1200000,
          "description": "Luxury villa perched on cliffs with uninterrupted Pacific Ocean views",
          "amenities": ["Ocean Views", "Infinity Pool", "Wine Cellar", "Helipad"],
          "isAvailable": true,
        },
        {
          "id": 23,
          "title": "Skyline Penthouse",
          "image": "assets/house6.jpg",
          "location": "Manhattan, NY",
          "bedrooms": 2,
          "bathrooms": 2,
          "area": "1,500 sq ft",
          "propertyType": "Penthouse",
          "category": "Residential",
          "rentPrice": 8500,
          "buyPrice": 2800000,
          "description": "Ultra-luxury penthouse with panoramic Manhattan skyline views",
          "amenities": ["Skyline Views", "Private Elevator", "Rooftop Terrace", "Concierge"],
          "isAvailable": true,
        },
        {
          "id": 24,
          "title": "Desert Oasis House",
          "image": "assets/house2.jpg",
          "location": "Palm Springs, CA",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,600 sq ft",
          "propertyType": "House",
          "category": "Residential",
          "rentPrice": 2800,
          "buyPrice": 480000,
          "description": "Modern desert home with mountain views and private pool",
          "amenities": ["Mountain Views", "Private Pool", "Desert Garden", "Outdoor Kitchen"],
          "isAvailable": true,
        },
      ],
      "Cabins": [
        {
          "id": 25,
          "title": "Yosemite Wilderness Cabin",
          "image": "assets/house 1.jpg",
          "location": "Yosemite, CA",
          "bedrooms": 2,
          "bathrooms": 1,
          "area": "800 sq ft",
          "propertyType": "Cabin",
          "category": "Residential",
          "rentPrice": 1800,
          "buyPrice": 280000,
          "description": "Authentic log cabin in the heart of Yosemite with wildlife viewing",
          "amenities": ["Wood Fireplace", "Wildlife Viewing", "Hiking Trails", "Bear Proof Storage"],
          "isAvailable": true,
        },
        {
          "id": 26,
          "title": "Smoky Mountain Retreat",
          "image": "assets/house2.jpg",
          "location": "Gatlinburg, TN",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,200 sq ft",
          "propertyType": "Cabin",
          "category": "Residential",
          "rentPrice": 2200,
          "buyPrice": 320000,
          "description": "Cozy mountain cabin with hot tub and mountain views",
          "amenities": ["Hot Tub", "Mountain Views", "Fireplace", "Game Room"],
          "isAvailable": true,
        },
        {
          "id": 27,
          "title": "Lakeside Log Cabin",
          "image": "assets/house3.jpg",
          "location": "Lake Arrowhead, CA",
          "bedrooms": 4,
          "bathrooms": 3,
          "area": "1,600 sq ft",
          "propertyType": "Cabin",
          "category": "Residential",
          "rentPrice": 3200,
          "buyPrice": 480000,
          "description": "Spacious log cabin with private lake access and boat dock",
          "amenities": ["Lake Access", "Boat Dock", "Fireplace", "Deck"],
          "isAvailable": true,
        },
        {
          "id": 28,
          "title": "Rustic A-Frame Cabin",
          "image": "assets/house5.jpg",
          "location": "Lake Tahoe, CA",
          "bedrooms": 2,
          "bathrooms": 1,
          "area": "900 sq ft",
          "propertyType": "Cabin",
          "category": "Residential",
          "rentPrice": 2000,
          "buyPrice": 350000,
          "description": "Charming A-frame cabin with loft bedroom and lake views",
          "amenities": ["Loft Bedroom", "Lake Views", "Wood Stove", "Deck"],
          "isAvailable": true,
        },
      ],
      "Mountains": [
        {
          "id": 29,
          "title": "Aspen Ski Chalet",
          "image": "assets/house5.jpg",
          "location": "Aspen, CO",
          "bedrooms": 5,
          "bathrooms": 4,
          "area": "2,800 sq ft",
          "propertyType": "House",
          "category": "Residential",
          "rentPrice": 6800,
          "buyPrice": 1200000,
          "description": "Luxury ski chalet with private ski lift access and mountain views",
          "amenities": ["Ski Lift Access", "Mountain Views", "Hot Tub", "Wine Cellar"],
          "isAvailable": true,
        },
        {
          "id": 30,
          "title": "Rocky Mountain Lodge",
          "image": "assets/house6.jpg",
          "location": "Estes Park, CO",
          "bedrooms": 4,
          "bathrooms": 3,
          "area": "2,200 sq ft",
          "propertyType": "Lodge",
          "category": "Residential",
          "rentPrice": 3800,
          "buyPrice": 680000,
          "description": "Rustic mountain lodge with hiking trails and wildlife viewing",
          "amenities": ["Hiking Trails", "Wildlife Viewing", "Fireplace", "Deck"],
          "isAvailable": true,
        },
        {
          "id": 31,
          "title": "Vail Village Condo",
          "image": "assets/house7.jpg",
          "location": "Vail, CO",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,400 sq ft",
          "propertyType": "Apartment",
          "category": "Residential",
          "rentPrice": 4200,
          "buyPrice": 850000,
          "description": "Ski-in/ski-out condo in the heart of Vail Village",
          "amenities": ["Ski Access", "Village Location", "Pool", "Spa"],
          "isAvailable": true,
        },
        {
          "id": 32,
          "title": "Telluride Mountain Home",
          "image": "assets/house6.jpg",
          "location": "Telluride, CO",
          "bedrooms": 3,
          "bathrooms": 2,
          "area": "1,800 sq ft",
          "propertyType": "House",
          "category": "Residential",
          "rentPrice": 5200,
          "buyPrice": 980000,
          "description": "Mountain home with panoramic valley views and ski access",
          "amenities": ["Valley Views", "Ski Access", "Hot Tub", "Fireplace"],
          "isAvailable": true,
        },
      ],
      "Nature stays": [
        {
          "id": 33,
          "title": "Redwood Treehouse",
          "image": "assets/house7.jpg",
          "location": "Mendocino, CA",
          "bedrooms": 1,
          "bathrooms": 1,
          "area": "700 sq ft",
          "propertyType": "Treehouse",
          "category": "Residential",
          "rentPrice": 2200,
          "buyPrice": 380000,
          "description": "Eco-friendly treehouse nestled in ancient redwood canopy",
          "amenities": ["Forest Views", "Solar Power", "Composting Toilet", "Hiking Trails"],
          "isAvailable": true,
        },
        {
          "id": 34,
          "title": "Glamping Safari Tent",
          "image": "assets/house 1.jpg",
          "location": "Joshua Tree, CA",
          "bedrooms": 1,
          "bathrooms": 1,
          "area": "400 sq ft",
          "propertyType": "Tent",
          "category": "Residential",
          "rentPrice": 1800,
          "buyPrice": 120000,
          "description": "Luxury glamping tent with desert views and stargazing deck",
          "amenities": ["Desert Views", "Stargazing Deck", "Outdoor Shower", "Fire Pit"],
          "isAvailable": true,
        },
        {
          "id": 35,
          "title": "Yurt Retreat",
          "image": "assets/house5.jpg",
          "location": "Oregon Coast, OR",
          "bedrooms": 2,
          "bathrooms": 1,
          "area": "800 sq ft",
          "propertyType": "Yurt",
          "category": "Residential",
          "rentPrice": 1600,
          "buyPrice": 180000,
          "description": "Traditional Mongolian yurt with ocean views and beach access",
          "amenities": ["Ocean Views", "Beach Access", "Wood Stove", "Deck"],
          "isAvailable": true,
        },
        {
          "id": 36,
          "title": "Eco-Friendly Dome",
          "image": "assets/house2.jpg",
          "location": "Sedona, AZ",
          "bedrooms": 1,
          "bathrooms": 1,
          "area": "500 sq ft",
          "propertyType": "Dome",
          "category": "Residential",
          "rentPrice": 2000,
          "buyPrice": 250000,
          "description": "Geodesic dome with red rock views and sustainable features",
          "amenities": ["Red Rock Views", "Solar Power", "Rainwater Collection", "Hiking Trails"],
          "isAvailable": true,
        },
      ],
      "Commercial Properties": [
        {
          "id": 37,
          "title": "Downtown Office Tower",
          "image": "assets/house 1.jpg",
          "location": "Downtown LA, CA",
          "bedrooms": 0,
          "bathrooms": 3,
          "area": "3,200 sq ft",
          "propertyType": "Office",
          "category": "Commercial",
          "rentPrice": 6800,
          "buyPrice": 1200000,
          "description": "Premium office space with city views and modern amenities",
          "amenities": ["City Views", "Parking", "Conference Rooms", "Cafeteria"],
          "isAvailable": true,
        },
        {
          "id": 38,
          "title": "Rodeo Drive Boutique",
          "image": "assets/house2.jpg",
          "location": "Beverly Hills, CA",
          "bedrooms": 0,
          "bathrooms": 2,
          "area": "1,200 sq ft",
          "propertyType": "Shop",
          "category": "Commercial",
          "rentPrice": 4500,
          "buyPrice": 950000,
          "description": "Luxury retail space on world-famous Rodeo Drive",
          "amenities": ["Street Access", "Display Windows", "Storage", "Security System"],
          "isAvailable": true,
        },
        {
          "id": 39,
          "title": "Tech Campus Building",
          "image": "assets/house3.jpg",
          "location": "Palo Alto, CA",
          "bedrooms": 0,
          "bathrooms": 6,
          "area": "8,500 sq ft",
          "propertyType": "Corporate",
          "category": "Commercial",
          "rentPrice": 18000,
          "buyPrice": 4200000,
          "description": "Modern corporate building in Silicon Valley with tech amenities",
          "amenities": ["Parking Garage", "Rooftop Deck", "Gym", "Cafeteria", "EV Charging"],
          "isAvailable": true,
        },
        {
          "id": 40,
          "title": "Distribution Warehouse",
          "image": "assets/house5.jpg",
          "location": "Ontario, CA",
          "bedrooms": 0,
          "bathrooms": 3,
          "area": "25,000 sq ft",
          "propertyType": "Building",
          "category": "Commercial",
          "rentPrice": 12000,
          "buyPrice": 2800000,
          "description": "Large distribution facility with loading docks and office space",
          "amenities": ["Loading Docks", "High Ceilings", "Office Space", "Security System"],
          "isAvailable": true,
        },
      ],
    };
  }
}
