Map<String, Map<String, String>> localized = {
  "EN": {
    "settings": "Settings",
    "editProfile": "Edit Profile",
    "appSettings": "App Settings",
    "languageOption": "Language Option",
    "mode": "Mode",
    "dark": "Dark",
    "light": "Light",
    "notification": "Notification",
    "help": "Help",
    "myAccount": "My Account",
    "payment": "Payment",
    "saved": "Saved",
    "privacy": "Privacy Policy",
    "termsConditions": "Terms & Conditions",
    "logout": "Log Out",
    "logoutConfirm": "Do you want to log out?",
    "yesLogout": "Yes, Logout",
    "cancel": "No, Cancel",
    "loggedOut": "You have been logged out",
    "paymentEnabled": "Enable Payments",
    "paymentEnabledOn": "Payments available",
    "paymentEnabledOff": "Payments disabled",
    "amount": "Amount (INR)",
    "method": "Payment Method",
    "note": "Note (optional)",
    "noteHint": "Purpose, order id, etc.",
    "payNow": "Pay Now",
    "processing": "Processing...",
    "history": "Transaction History",
    "noTxns": "No transactions yet",
    "invalidAmount": "Please enter a valid amount",
    "paymentSuccessTitle": "Payment Successful",
    "paymentSuccessMsg": "Your payment has been completed.",
    "txnId": "Transaction ID",
    "ok": "OK",
    "clear": "Clear",
    "clearHistory": "Clear Transactions",
    "clearConfirmMsg": "Do you want to delete all transactions?",
    "cleared": "Transactions cleared",
  },
  "TE": {
    "settings": "అమరికలు",
    "editProfile": "ప్రొఫైల్ సవరించు",
    "appSettings": "యాప్ అమరికలు",
    "languageOption": "భాష ఎంపిక",
    "mode": "రూపం",
    "dark": "డార్క్",
    "light": "లైట్",
    "notification": "నోటిఫికేషన్",
    "help": "సహాయం",
    "myAccount": "నా ఖాతా",
    "payment": "చెల్లింపు",
    "saved": "భద్రపరచినవి",
    "privacy": "గోప్యతా విధానం",
    "termsConditions": "నిబంధనలు మరియు షరతులు",
    "logout": "లాగ్ అవుట్",
    "logoutConfirm": "మీరు లాగ్ అవుట్ కావాలనుకుంటున్నారా?",
    "yesLogout": "అవును, లాగ్ అవుట్",
    "cancel": "కాదు, రద్దు",
    "loggedOut": "మీరు లాగ్ అవుట్ అయ్యారు",
    "paymentEnabled": "చెల్లింపులు ప్రారంభించు",
    "paymentEnabledOn": "చెల్లింపులు అందుబాటులో ఉన్నాయి",
    "paymentEnabledOff": "చెల్లింపులు నిలిపివేయబడ్డాయి",
    "amount": "మొత్తం (INR)",
    "method": "చెల్లింపు విధానం",
    "note": "గమనిక (ఐచ్చికం)",
    "noteHint": "ఉద్దేశ్యం, ఆర్డర్ ఐడి మొదలైనవి",
    "payNow": "ఇప్పుడు చెల్లించు",
    "processing": "ప్రాసెసింగ్...",
    "history": "లావాదేవీల చరిత్ర",
    "noTxns": "ఇప్పటివరకు లావాదేవీలు లేవు",
    "invalidAmount": "దయచేసి సరైన మొత్తాన్ని ఇవ్వండి",
    "paymentSuccessTitle": "చెల్లింపు విజయవంతం",
    "paymentSuccessMsg": "మీ చెల్లింపు పూర్తయింది.",
    "txnId": "లావాదేవీ ఐడి",
    "ok": "సరే",
    "clear": "క్లీర్",
    "clearHistory": "లావాదేవీలు తొలగించు",
    "clearConfirmMsg": "అన్ని లావాదేవీలను తొలగించాలా?",
    "cleared": "లావాదేవీలు తొలగించబడ్డాయి",
  }
};

Map<String, String> localizedText(String lang) {
  return localized[lang] ?? localized["EN"]!;
}